---
framework: jest
preRun:
  command:
    - yarn
preMerge:
  pattern:
    - "app/javascript/mastodon/features/emoji/__tests__/emoji_index-test.js"
postMerge:
  pattern:
    - "app/javascript/mastodon/features/emoji/__tests__/emoji_index-test.js"
postRun:
  command:
    - yarn --version
version: 1.0
