---
framework: jest
preRun:
  command:
    - yarn install
preMerge:
  env:
    NODE_ENV: test
  pattern:
    - "app/javascript/mastodon/features/emoji/__tests__/emoji_index-test.js"
postMerge:
  env:
    NODE_ENV: test
  pattern:
    - "app/javascript/mastodon/features/emoji/__tests__/emoji_index-test.js"
postRun:
  command:
    - yarn --version
version: 1.0
